In [18]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])
type(a1)

numpy.ndarray

In [7]:
a2 = np.arange(10)

In [8]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a3 = np.zeros((2 , 3))
a4 = np.ones((2, 1))

In [23]:
from IPython.display import display
display(a3);display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1.],
       [1.]])

In [27]:
a5 = np.linspace(1,2,10)
display(a5)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [28]:
a5.dtype

dtype('float64')

# Dimensión de un Array

In [29]:
display(a1)

array([1, 2, 3])

In [30]:
a1.shape

(3,)

In [31]:
display(a3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
a3.shape

(2, 3)

In [47]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [36]:
np.array_equal(a1D,a2D)

False

In [48]:
new_dims = (1,a1D.shape[0])
display(new_dims)
a = a1D.reshape(new_dims)
display(a)
display(a2D)

(1, 3)

array([[1, 2, 3]])

array([[1, 2, 3]])

In [50]:
np.array_equal(a,a2D)

True

# Acceso a elementos y Slicing

In [52]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [54]:
a[2,1]

10

In [56]:
a = np.arange(10)
b = np.eye(3)
display(a);display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
a[:5]

array([0, 1, 2, 3, 4])

In [59]:
b[0:3,1]

array([0., 1., 0.])

In [60]:
b[2,0:3]

array([0., 0., 1.])

In [61]:
b[:,:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Operaciones aritméticas en Numpy

In [66]:
a = np.arange(4)

print("a      =", a)
print("a + 5  =", a + 5)
print("a - 5  =", a - 5)
print("a * 5  =", a * 5)
print("a / 2  =", a / 2)
print("a // 2 =", a // 2)
print("a ** 2 =", a ** 2)
print("a % 2  =", a % 2)


a      = [0 1 2 3]
a + 5  = [5 6 7 8]
a - 5  = [-5 -4 -3 -2]
a * 5  = [ 0  5 10 15]
a / 2  = [0.  0.5 1.  1.5]
a // 2 = [0 0 1 1]
a ** 2 = [0 1 4 9]
a % 2  = [0 1 0 1]


In [67]:
a+a

array([0, 2, 4, 6])

In [71]:
a = np.arange(4)
b = np.arange(1,5)

display(np.exp(a))
display(np.log(b))
display(np.sqrt(a))
display(np.greater(a,b))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

In [72]:
a

array([0, 1, 2, 3])

In [73]:
b

array([1, 2, 3, 4])

# Rendimiento

In [76]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i = 0
for el in a:
    b[i] = el+el
    i+=1



566 ms ± 80.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [77]:
%%timeit
a+a

866 ns ± 113 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Estadísticas y aleatoridad

In [79]:
a = np.arange(10)

display(np.mean(a))
display(np.median(a))

4.5

4.5

In [80]:
np.percentile(a,40)

3.6

In [81]:
np.random.random(10)

array([0.82597719, 0.46343166, 0.0086762 , 0.91428351, 0.5247184 ,
       0.64653524, 0.99352762, 0.15698175, 0.08079132, 0.84088574])